version: "3.7"

networks:
  app-network:
    driver: bridge

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
      args:
        user: www
        uid: 1000
    image: laravel8
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes: 
      - ./src:/var/www
    networks: 
      - app-network
        
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_NAME: mysql
    volumes:
      - ./docker-data/mysql/init:/docker-entrypoint-initdb.d
      - ./docker-data/mysql/data:/var/lib/mysql:delegated
    networks:
      - app-network
        
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports: 
      - 8081:80
    volumes: 
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks: 
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    expose:
      - 80
    ports:
      - 8082:80
    networks:
      - app-network
        