version: '3.7'
services:
  nginx:
    image: nginx:alpine
    container_name: gateway-nginx
    restart: unless-stopped
    expose:
      - "80"
    ports:
      - 8082:80
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    links:
      - app
    networks:
      - localNetwork

  app:
    image: laravel
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: laravel
    expose:
      - 9000
    working_dir: /var/www/
    volumes:
      - ./:/var/www

    networks:
      - localNetwork

networks:
  localNetwork:
    driver: bridge